models:
# Table: Fact Merchandise Exports
  - name: fact_merchandise_exports
    description: "This model contains the merchandise export data from the ABS."
    config:
      contract: { enforced: true }
    columns:
      - name: id
        description: "The primary key for the table."
        data_type: text
        tests:
          - not_null
          - unique          
          - dbt_constraints.primary_key:
              config:
                severity: error
                message: The id must be unique and not null.
      - name: date_key
        description: "The date of the export."
        data_type: integer
        tests:
          - not_null
          - relationships:
              to: ref('dim_date')
              field: date_key
              config:
                severity: error
                message: The date_key must exist in the dim_date table.
      - name: goods_key
        description: "The identifier for the goods."
        data_type: text
        tests:
          - not_null
          - relationships:
              to: ref('dim_goods')
              field: goods_key
              config:
                severity: error
                message: The goods_key must exist in the dim_goods table.
      - name: amount_in_million_aud
        description: "The amount of goods exported in million AUD."
        data_type: numeric
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100000
              config:
                severity: warn
                message: The amount_in_million_aud must be between 0 and 100,000.

# Table: Fact Merchandise Imports
  - name: fact_merchandise_imports
    description: "This model contains the merchandise imports data from the ABS."
    config:
      contract: { enforced: true }
    columns:
      - name: id
        description: "The primary key for the table."
        data_type: text
        tests:
          - not_null
          - unique          
          - dbt_constraints.primary_key:
              config:
                severity: error
                message: The id must be unique and not null.
      - name: date_key
        description: "The date of the import."
        data_type: integer
        tests:
          - not_null
          - relationships:
              to: ref('dim_date')
              field: date_key
              config:
                severity: error
                message: The date_key must exist in the dim_date table.
      - name: goods_key
        description: "The identifier for the goods."
        data_type: text
        tests:
          - not_null
          - relationships:
              to: ref('dim_goods')
              field: goods_key
              config:
                severity: error
                message: The goods_key must exist in the dim_goods table.
      - name: amount_in_million_aud
        description: "The amount of goods imported in million AUD."
        data_type: numeric
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100000
              config:
                severity: warn
                message: The amount_in_million_aud must be between 0 and 100,000.

# Table: Fact Merchandise Exports by Country
  - name: fact_merchandise_exports_by_country
    description: "This model contains the merchandise export data by country from the ABS."
    config:
      contract: { enforced: true }
    columns:
      - name: id
        description: "The primary key for the table."
        data_type: text
        tests:
          - not_null
          - unique          
          - dbt_constraints.primary_key:
              config:
                severity: error
                message: The id must be unique and not null.
      - name: date_key
        description: "The date of the export."
        data_type: integer
        tests:
          - not_null
          - relationships:
              to: ref('dim_date')
              field: date_key
              config:
                severity: error
                message: The date_key must exist in the dim_date table.
      - name: country_key
        description: "The identifier for the countries."
        data_type: text
        tests:
          - not_null
          - relationships:
              to: ref('dim_country')
              field: country_key
              config:
                severity: error
                message: The country_key must exist in the dim_country table.
      - name: amount_in_million_aud
        description: "The amount of goods exported in million AUD."
        data_type: numeric
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100000
              config:
                severity: warn
                message: The amount_in_million_aud must be between 0 and 100,000.

# Table: Fact Merchandise Imports by Country
  - name: fact_merchandise_imports_by_country
    description: "This model contains the merchandise import data by country from the ABS."
    config:
      contract: { enforced: true }
    columns:
      - name: id
        description: "The primary key for the table."
        data_type: text
        tests:
          - not_null
          - unique          
          - dbt_constraints.primary_key:
              config:
                severity: error
                message: The id must be unique and not null.
      - name: date_key
        description: "The date of the import."
        data_type: integer
        tests:
          - not_null
          - relationships:
              to: ref('dim_date')
              field: date_key
              config:
                severity: error
                message: The date_key must exist in the dim_date table.
      - name: country_key
        description: "The identifier for the countries."
        data_type: text
        tests:
          - not_null
          - relationships:
              to: ref('dim_country')
              field: country_key
              config:
                severity: error
                message: The country_key must exist in the dim_country table.
      - name: amount_in_million_aud
        description: "The amount of goods imported in million AUD."
        data_type: numeric
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100000
              config:
                severity: warn
                message: The amount_in_million_aud must be between 0 and 100,000.

# Table: Fact Merchandise Exports by Industry
  - name: fact_merchandise_exports_by_industry
    description: "This model contains the merchandise export data by industry from the ABS."
    config:
      contract: { enforced: true }
    columns:
      - name: id
        description: "The primary key for the table."
        data_type: text
        tests:
          - not_null
          - unique          
          - dbt_constraints.primary_key:
              config:
                severity: error
                message: The id must be unique and not null.
      - name: date_key
        description: "The date of the export."
        data_type: integer
        tests:
          - not_null
          - relationships:
              to: ref('dim_date')
              field: date_key
              config:
                severity: error
                message: The date_key must exist in the dim_date table.
      - name: industry_key
        description: "The identifier for the industries."
        data_type: text
        tests:
          - not_null
          - relationships:
              to: ref('dim_industry')
              field: industry_key
              config:
                severity: error
                message: The industry_key must exist in the dim_industry table.
      - name: amount_in_million_aud
        description: "The amount of goods exported in million AUD."
        data_type: numeric
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100000
              config:
                severity: warn
                message: The amount_in_million_aud must be between 0 and 100,000.
                
# Table: Fact Merchandise Imports by Industry
  - name: fact_merchandise_imports_by_industry
    description: "This model contains the merchandise Imports data by industry from the ABS."
    config:
      contract: { enforced: true }
    columns:
      - name: id
        description: "The primary key for the table."
        data_type: text
        tests:
          - not_null
          - unique          
          - dbt_constraints.primary_key:
              config:
                severity: error
                message: The id must be unique and not null.
      - name: date_key
        description: "The date of the import."
        data_type: integer
        tests:
          - not_null
          - relationships:
              to: ref('dim_date')
              field: date_key
              config:
                severity: error
                message: The date_key must exist in the dim_date table.
      - name: industry_key
        description: "The identifier for the industries."
        data_type: text
        tests:
          - not_null
          - relationships:
              to: ref('dim_industry')
              field: industry_key
              config:
                severity: error
                message: The industry_key must exist in the dim_industry table.
      - name: amount_in_million_aud
        description: "The amount of goods imported in million AUD."
        data_type: numeric
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100000
              config:
                severity: warn
                message: The amount_in_million_aud must be between 0 and 100,000.

# Table: Fact Merchandise Exports by States
  - name: fact_merchandise_exports_by_states
    description: "This model contains the merchandise export data by states from the ABS."
    config:
      contract: { enforced: true }
    columns:
      - name: id
        description: "The primary key for the table."
        data_type: text
        tests:
          - not_null
          - unique          
          - dbt_constraints.primary_key:
              config:
                severity: error
                message: The id must be unique and not null.
      - name: date_key
        description: "The date of the export."
        data_type: integer
        tests:
          - not_null
          - relationships:
              to: ref('dim_date')
              field: date_key
              config:
                severity: error
                message: The date_key must exist in the dim_date table.
      - name: state_territory_key
        description: "The identifier for the states."
        data_type: text
        tests:
          - not_null
          - relationships:
              to: ref('dim_states')
              field: state_territory_key
              config:
                severity: error
                message: The industry_key must exist in the dim_states table.
      - name: amount_in_million_aud
        description: "The amount of goods exported in million AUD."
        data_type: numeric
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100000
              config:
                severity: warn
                message: The amount_in_million_aud must be between 0 and 100,000.

# Table: Fact Merchandise Imports by States
  - name: fact_merchandise_imports_by_states
    description: "This model contains the merchandise import data by states from the ABS."
    config:
      contract: { enforced: true }
    columns:
      - name: id
        description: "The primary key for the table."
        data_type: text
        tests:
          - not_null
          - unique          
          - dbt_constraints.primary_key:
              config:
                severity: error
                message: The id must be unique and not null.
      - name: date_key
        description: "The date of the import."
        data_type: integer
        tests:
          - not_null
          - relationships:
              to: ref('dim_date')
              field: date_key
              config:
                severity: error
                message: The date_key must exist in the dim_date table.
      - name: state_territory_key
        description: "The identifier for the states."
        data_type: text
        tests:
          - not_null
          - relationships:
              to: ref('dim_states')
              field: state_territory_key
              config:
                severity: error
                message: The industry_key must exist in the dim_states table.
      - name: amount_in_million_aud
        description: "The amount of goods exported in million AUD."
        data_type: numeric
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100000
              config:
                severity: warn
                message: The amount_in_million_aud must be between 0 and 100,000.

# Table: Dim States
  - name: dim_states
    description: "This model contains the list of states and territories of Australia."
    config:
      contract: { enforced: true }
    columns:
      - name: state_territory_key
        description: "The primary key for the table."
        data_type: text
        tests:
          - not_null
          - unique          
          - dbt_constraints.primary_key:
              config:
                severity: error
                message: The state_territory_key must be unique and not null.
      - name: state_territory
        description: "The name of the state or territory."
        data_type: text
        tests:
          - not_null
          - unique

# Table: Dim Country
  - name: dim_country
    description: "This model contains the list of the countries."
    config:
      contract: { enforced: true }
    columns:
      - name: country_key
        description: "The primary key for the table."
        data_type: text
        tests:
          - not_null
          - unique          
          - dbt_constraints.primary_key:
              config:
                severity: error
                message: The country_key must be unique and not null.
      - name: country
        description: "The name of the country."
        data_type: text
        tests:
          - not_null
          - unique

# Table: Dim Goods
  - name: dim_goods
    description: "This model contains the list of goods."
    config:
      contract: { enforced: true }
    columns:
      - name: goods_key
        description: "The primary key for the table."
        data_type: text
        tests:
          - not_null
          - unique          
          - dbt_constraints.primary_key:
              config:
                severity: error
                message: The goods_key must be unique and not null.
      - name: goods
        description: "The name of the goods."
        data_type: text
        tests:
          - not_null
          - unique

# Table: Dim Industry
  - name: dim_industry
    description: "This model contains the list of industries."
    config:
      contract: { enforced: true }
    columns:
      - name: industry_key
        description: "The primary key for the table."
        data_type: text
        tests:
          - not_null
          - unique          
          - dbt_constraints.primary_key:
              config:
                severity: error
                message: The industry_key must be unique and not null.
      - name: industry
        description: "The name of the industry."
        data_type: text
        tests:
          - not_null
          - unique

# Table: Dim Date
  - name: dim_date
    description: "This model contains the dates."
    config:
      contract: { enforced: true }
    columns:
      - name: date_key
        description: "The primary key for the table."
        data_type: integer
        tests:
          - not_null
          - unique          
          - dbt_constraints.primary_key:
              config:
                severity: error
                message: The date_key must be unique and not null.
      - name: date
        description: "The date."
        data_type: date
        tests:
          - not_null
          - unique
      - name: year
        description: "The year."
        data_type: integer
        tests:
          - not_null
      - name: month
        description: "The month."
        data_type: integer
        tests:
          - not_null
      - name: day
        description: "The day."
        data_type: integer
        tests:
          - not_null
      - name: quarter
        description: "The quarter."
        data_type: integer
        tests:
          - not_null
      - name: Day_Name
        description: "The name of the day."
        data_type: text
        tests:
          - not_null
      - name: Month_Name
        description: "The name of the month."
        data_type: text
        tests:
          - not_null
      - name: Short_Month_Name
        description: "The short name of the month."
        data_type: text
        tests:
          - not_null